import { v4 as uuidv4 } from "uuid";
export const wordType = [
	{ key: uuidv4(), vocabulary: "verb" },
	{ key: uuidv4(), vocabulary: "adjective" },
	{ key: uuidv4(), vocabulary: "pronoun" },
	{ key: uuidv4(), vocabulary: "adverb" },
	{ key: uuidv4(), vocabulary: "preposition" },
	{ key: uuidv4(), vocabulary: "conjunction" },
	{ key: uuidv4(), vocabulary: "organs" },
	{ key: uuidv4(), vocabulary: "body" },
	{ key: uuidv4(), vocabulary: "health" },
	{ key: uuidv4(), vocabulary: "places" },
	{ key: uuidv4(), vocabulary: "shopping" },
	{ key: uuidv4(), vocabulary: "nature" },
	{ key: uuidv4(), vocabulary: "food" },
	{ key: uuidv4(), vocabulary: "feeling" },
	{ key: uuidv4(), vocabulary: "clothes" },
	{ key: uuidv4(), vocabulary: "animal" },
	{ key: uuidv4(), vocabulary: "kitchen" },
	{ key: uuidv4(), vocabulary: "fruit" },
	{ key: uuidv4(), vocabulary: "vegetable" },
];
